<?php

namespace Database\Seeders;

use App\Models\Division;
use App\Models\Group;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HeadOfficeDepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    private function getColumnId(String $column, String $name)
    {
        switch ($column) {
            case 'group':
                $model = Group::class;
                break;
            case 'division':
                $model = Division::class;
                break;
            default:
                $model = null;
                break;
        }

        if ($name === 'N/A') {
            return null;
        }

        $data = $model::where('name', $name)->first();

        return $data->id;
    }

    public function run(): void
    {
        DB::table('departments')->insert([
            ["name" => "Field Audit Department", "code" => "FiAD","description" => "The Field Audit Department is responsible for the regular, targeted scope, remote, and directed audits of BMI Branches and BFC Clusters (credit investigation and collection services). This consists of two (2) audit sections which are under the supervision of the Department Head and each section is composed of a Section Head, Audit Officers or Associates.", "group_id" =>  $this->getColumnId('group', "Internal Audit Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Head Office Audit Department", "code" => "HOAD","description" => "The Head Office Audit Department is responsible for the regular, targeted scope and directed audits of all BMI Head Office and Loan Units. The Department consists of three (3) sections namely Loans Audit Section, Support Units Audit Section, and Control Units and Treasury Audit Section. All sections are under the supervision of the Department Head and each is composed of a Section Head and Audit Officers.", "group_id" =>  $this->getColumnId('group', "Internal Audit Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Information Technology Audit Department", "code" => "ITAD","description" => "The Information Technology Audit Department is responsible for the assessment of the Bank’s technology controls", "group_id" =>  $this->getColumnId('group', "Internal Audit Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Quality Assurance Department", "code" => "QAD","description" => "The Quality Assurance Department is created to assist the IAG Head in the evaluation of the IAG's conformance with the definition of Internal Auditing and The Standards and in evaluating whether the Internal Auditors apply the Code of Ethics. This Department consists of Quality Assurance Associates and Administrative Associate under the supervision of the Department Head.", "group_id" =>  $this->getColumnId('group', "Internal Audit Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Anti-Money Laundering Department", "code" => "AMLD","description" => "The Department is responsible for the management, development, implementation and maintenance of the Bank’s Money Laundering and Terrorist Financing Prevention Program (MTPP) to ensure compliance with the Anti-Money Laundering Act (AMLA), as amended, including its Implementing Rules and Regulations (IRR).", "group_id" =>  $this->getColumnId('group', "Compliance Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Regulatory Compliance Department", "code" => "RCD-CG","description" => "The Department is responsible for the development, implementation, management, and maintenance of the Bank’s Compliance Program to ensure compliance with the Bangko Sentral ng Pilipinas (BSP), Philippine Deposit Insurance Corp (PDIC), Securities and Exchange Commission (SEC) and other regulatory agencies.", "group_id" =>  $this->getColumnId('group', "Compliance Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Operational Risk Management Department", "code" => "ORMD","description" => "ORMD plays a vital role in identifying, assessing, measuring, mitigating and monitoring potential operational risk within the Bank, including developing and maintaining a framework to manage operational risks, providing guidelines to the Business Units and reporting risk exposures to the Senior Management, Risk Oversight Committee and to the Board.", "group_id" =>  $this->getColumnId('group', "Risk Management Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Credit Risk Management Department", "code" => "CRMD","description" => "CRMD oversees the implementation of Board-approved credit risk policies and risk appetite, ensuring effective management of lending exposure risks. In accordance with the Credit Risk Management Manual, BMI’s Credit Risk Appetite and governing regulations.", "group_id" =>  $this->getColumnId('group', "Risk Management Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Market & Liquidity Risk Management Department", "code" => "MLRMD","description" => "Market & Liquidity Risk Management Department", "group_id" =>  $this->getColumnId('group', "Risk Management Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Customer Experience Management Department", "code" => "CEMD","description" => "CEMD is tasked to spearhead, collaborate with Business & Support units, monitor, and ensure that the Bank's brand, products, services, processes, communication strategies, marketing campaigns, action plans, and/or programs are focused on creating good customer experiences across all of the Bank’s channels/touch points.; The Department is also responsible for the implementation of the Bank’s Consumer Protection Framework, as mandated by the Bangko Sentral ng Pilipinas (BSP). These includes but not limited to catering to Customer request, queries, and complaints (RQC); regular consolidation, comparison, and analysis of received complaints; preparation and submission of Financial Consumer Protection Assistance Mechanism (FCPAM)-related reports to the Board-level Committees.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Legal Advisory & Documentation Department", "code" => "LADD","description" => "Provides legal advise on all legal issues that directly affect the Bank's rights, interests, reputation and objectives in compliance with prevailing law, jurisprudence, and administrative rules and regulations.; Prepares and reviews legal documents and contracts, as well as correspondences, where the Bank shall be a party or will have an interest in.; Revises standard Bank documentation.", "group_id" =>  $this->getColumnId('group', "Legal Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Litigation & Other Legal Support Department", "code" => "LLSD","description" => "Handles and controls all legal actions to be filed by or filed against the Bank as well as its directors and/or officers in relation to the performance of their official functions.; Handles and manages all cases and accounts for litigation, including cases involving bank employees, except those collection cases that should be properly endorsed to the Collection and External Agency Department (CEAD) in accordance with the Bank's existing policies and procedures. May also act as legal support in corporate housekeeping and other matters as may be assigned from time-to-time.", "group_id" =>  $this->getColumnId('group', "Legal Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Area 1 North Luzon and DOSRI", "code" => "A1NLD","description" => "all business loan accounts covering North Luzon", "group_id" =>  $this->getColumnId('group', "Corporate & Retail Lending Group"), "division_id" => $this->getColumnId('division',"Commercial Business Lending Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Area 2 NCR and Syndicated", "code" => "A2NS","description" => "all business loan accounts covering NCR including Syndicated Loans and DOSRI   accounts", "group_id" =>  $this->getColumnId('group', "Corporate & Retail Lending Group"), "division_id" => $this->getColumnId('division',"Commercial Business Lending Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Area 3 South Luzon and Vismin", "code" => "A3SLV","description" => "all business loan accounts covering South Luzon, Visayas and Mindanao", "group_id" =>  $this->getColumnId('group', "Corporate & Retail Lending Group"), "division_id" => $this->getColumnId('division',"Commercial Business Lending Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Real Estate Department", "code" => "RED","description" => "Handles developmental loans and house construction of real estate developers including accreditation of developers for end-user financing and handles all housing loans from accredited developers and referred by branches.", "group_id" =>  $this->getColumnId('group', "Corporate & Retail Lending Group"), "division_id" => $this->getColumnId('division',"Real Estate & Consumer Lending Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Consumer Department", "code" => "CD","description" => "handles all consumer loans.", "group_id" =>  $this->getColumnId('group', "Corporate & Retail Lending Group"), "division_id" => $this->getColumnId('division',"Real Estate & Consumer Lending Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "MSLD Area 1", "code" => "MSLDA1","description" => "handles the marketing and processing of all Microfinance & Power Negosyo Enterprise Loans In North and Central Luzon, NCR North and Rizal Province. This includes own solicited accounts, referred by BMI branches and referred by sister companies. ", "group_id" =>  $this->getColumnId('group', "Corporate & Retail Lending Group"), "division_id" => $this->getColumnId('division',"Micro & Small Lending Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "MSLD Area 2", "code" => "MSLDA2","description" => "handles the marketing and processing of all Microfinance and Power Negosyo Enterprise Loans in South Luzon, South NCR, Visayas and Mindanao. This includes own solicited accounts, referred by BMI branches and referred by sister companies.", "group_id" =>  $this->getColumnId('group', "Corporate & Retail Lending Group"), "division_id" => $this->getColumnId('division',"Micro & Small Lending Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Treasury Trading Department", "code" => "TTD","description" => "Treasury Trading Department is responsible for the following: a)Buying and/or selling of debt securities and investments (e.g. Retail Treasury Bonds, Fixed Rate Treasury Notes, and high grade bonds and notes with at least AAA rating) for proprietary purposes b)Sending daily quotation of available Government Securities to Branches and trading in behalf of the investors  c)Managing and monitoring the investment portfolio, taking into consideration the limits approved by the Board, ensuring satisfactory return of investments as well as compliance with internal and external policies and regulations.", "group_id" =>  $this->getColumnId('group', "Treasury Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Fund Management Department", "code" => "FMD","description" => "FUNCTIONAL DESCRIPTION\n1)Ensure adequate liquidity position of the Bank.\n2)Ensure optimized investment of excess funds.\n3)Ensure that current/savings accounts maintained at depository banks and cash-in-vault of branches are kept within the approved levels.\n4)Ensure proper management of interest rates. Reviews and updates interest rate on loans and deposits regularly.\n5)Ensure timely release of funds required by branches, operation groups and third parties.\n6)Ensure compliance with regulatory requirements (i.e., reserve requirements, single borrower’s limit, agrarian law and remittance of payments to Bureau of Internal Revenue).", "group_id" =>  $this->getColumnId('group', "Treasury Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Treasury Marketing Department", "code" => "TMD","description" => "The Department's primary responsibilities are as follows: a)Solicit clients to build a portfolio and establish relationship with them. It's target market are those individuals or selected group of individuals or businesses that require preferential treatment or personalized services;", "group_id" =>  $this->getColumnId('group', "Treasury Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Loans Management Department", "code" => "LMD","description" => "The Loan Management Department is responsible for the following functions:\na.Evaluation, processing and account termination of fully paid MCL Borrower.\nb.Payment processing and application.\nc.Payment Adjustment and account maintenance.\nd.Tagging and Termination of Repo Sale \ne.Releasing of Statement of Account (SOA) of requesting MCL Borrower\n", "group_id" =>  $this->getColumnId('group', "Loans Operations Group – Consumer"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Loan Operations Review & Support Department", "code" => "LORSD","description" => "Ensures that the operations and transactional activities of LOG-C and Outsourced\nCompanies are aligned with the bank's standard policies, procedures and organizational targets.; In-charged on activities relative to motorcycle loan transactions that require field checking or verification.; Conducts detection and investigation of early red-flag indicators or potential fraud in the motorcycle loan (MCL) accounts and transactions.", "group_id" =>  $this->getColumnId('group', "Loans Operations Group – Consumer"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Credit Authorization Department", "code" => "CAD","description" => "The Credit Authorization Department or CAD is the functional department responsible for the timely, proper thorough review and approval of all credit applications related to motorcycle loans (MCL) and consumer loans (Personal Loan, Expanded Motor Loan & Motorcycle Salary Loan) ", "group_id" =>  $this->getColumnId('group', "Loans Operations Group – Consumer"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Loans Operations Department 1", "code" => "LOD1","description" => "Ensure that loan documents of both MCL and non-MCL are complete and accurate prior loan release, see to it that the documents are safekeep and free from any unauthotize usage.", "group_id" =>  $this->getColumnId('group', "Loans Operations Group – Consumer"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Outbound Sales and Collection Management Department", "code" => "OSCMD","description" => "Outbound Sales and Collection Management Department", "group_id" =>  $this->getColumnId('group', "Repo Marketing & Disposal Management Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Remedial & Disposal Department", "code" => "RDD","description" => "The Remedial and Disposal Department (CRDD) handles the remedial of endorsed past due Business and Housing loan accounts of CRLG, disposal and management of acquired assets (Real estate properties)/Ropa in accordance with bank policies and within the required turn-around-time.", "group_id" =>  $this->getColumnId('group', "Repo Marketing & Disposal Management Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Remedial Management & Disposal Department", "code" => "RMDD","description" => "Its main function is to supervise the overall operations of acquired Repo Motorcycle inventory and disposal.", "group_id" =>  $this->getColumnId('group', "Repo Marketing & Disposal Management Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Remedial Collection Department", "code" => "RCD","description" => "Remedial Collection Department (RCD) shall be responsible for the implementation of appropriate remedial strategies and action plans aimed at collecting the amount due and payable, to achieve full recovery of the motorcycle loan (MCL) and non-collaterized MSME loan, or to collect, recover and restore up past due accounts to a sound standing in order to minimize potential losses of the Bank.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Remedial Collection Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Collections and External Accounts Department", "code" => "CEAD","description" => "Endorses and monitors the performance of our external collection agencies, where we outsource collection functions, after all collection efforts have been exhausted by in-house collectors. Files small claims cases, monitors development of cases, and represents the Bank as complainant/plaintiff. Execute court decisions against our borrowers to recover amount equivalent to the Bank's total claim. ", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Remedial Collection Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Loans Operations Department 2", "code" => "LOD2","description" => "The Loans Operations Department 2 (LOD 2) is the functional unit responsible for the timely  proper, and complete execution of the booking & releasing of loans, registration & annotation of mortgage, management of insurances and safekeeping of loan and collateral documents for business and real estate loans from the time the Financial Package is approved and loan proceeds are released until the loan obligation is fully paid.", "group_id" =>  $this->getColumnId('group', "Loans & Treasury Operations Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Institutional Borrowings Department", "code" => "IBD","description" => "The Institutional Borrowings Department (IBD) is directly incharge of processing the guaranty application for qualified Business and Housing loans Borrowers with Philguaranty. The Department is the one's working on the guaranty renewal, enrollment and claims as well as documentation. The Department is coordinating with various government Lending institutions (LBP, DBP, SBCorp and BSP) in terms of Credit Line renewal, and availments. The Department also acts as the liason of the Bank in terms complying with all the needed documents needed by the Lending Institutions  and Guarantor mentioned above. ", "group_id" =>  $this->getColumnId('group', "Loans & Treasury Operations Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Consumer Credit Department", "code" => "CCrD","description" => "Performs credit evaluation; renders credit decision based on respective delegated credit authority limits and recommends appropriate credit action for consumer loan products namely: Auto, Housing, Luxury Bike, Power Payday, Doctors' and Seafarers' Loans. ", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Credit Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Credit Evaluation & Policy Department", "code" => "CEPD","description" => "The Department has three distinct functions: (1) the Credit Policy Formulation (2) Evaluation function and (3) Documentation review function.\nThe Department is responsible for the formulation of Credit Policy, providing uniform understanding and consistent application of credit policies and procedures in granting Business Loans. Also, CEPD serves as Secretariat to SubCC and prepares summary of evaluation to endorsing body (sub-Credit Committee) for approval by the appropriate approving body. ", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Credit Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Micro Small Credit Department", "code" => "MSCD","description" => "Evaluates and approves of micro and Power Negosyo Enterprise Loans. ", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Credit Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Credit Investigation Department", "code" => "CrID","description" => "Conducts credit investigation of prospective borrowers (non-motorcycle loans). Includes Field and Desk verification that determines a firm's and/or individual's financial standing, credit standing, character and its integrity.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Credit Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Credit Appraisal Department", "code" => "CrAD","description" => "It is primarily tasked to render sound value to the property being offered as collateral as well as to assess the quality (acceptability) within the parameters of the bank's policies and guidelines. The appraisal report generated provides an incremental protection being the second way out and place the Bank in a stronger negotiating position based on the soundness and acceptability of the borrower's collateral. They also coordinate and review appraisal works performed by accredited external appraiser companies.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Credit Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Branch Banking Operations Department", "code" => "BBOD","description" => "Manages the overall operations of branches and monitors their strict compliance with the Bank's policies and procedures as well as the rules and regulations of government regulatory agencies.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Branch & Central Operations Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Central Support Operations Department", "code" => "CSOD","description" => "Supervises CCVU, PWCPU and E-Banking Unit; Monitors the strict compliance of units with the Bank's policies and procedures as well as the rules and regulations of government regulatory agencies; Approves transactions of units based on the approved authority of limits, if needed", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Branch & Central Operations Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Human Resources Department", "code" => "HRD","description" => "The department is primarily responsible for overseeing and managing the Bank's Human Resources core processes - Sourcing and Recruitment, Benefits Administration and Monitoring, HR Policy Formulation and Implementation, Human Resources Information System (HRIS), Employee Discipline and Labor Relations, Corporate Social Responsibility (CSR) Projects, Job Evaluation and Salary Review.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Organizational and People Development Department", "code" => "OPDD","description" => "The department is primarily responsible for identification, development and assessment of appropriate Organizational Development (OD) Interventions based on the Bank’s directions and employees’ needs. ", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "General Services Admin Department", "code" => "GSAD","description" => "To formulate, implement and ensure conformity with policies and procedures related to the management and maintenance of the Bank's furniture, fixtures and equipment, procurement of goods, maintenance services and providing other services such as communication, insurance, and logistics.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Safety & Security Department", "code" => "SSD","description" => "The Department is responsible for the safety and security of the Bank through direct supervision of security agencies & alarm providers and through the development and execution of all Safety and Security programs of the Bank. It ensures full compliance with BSP and Local Government regulations as far as safety and security requirements of the bank are concerned. The Safety & Security Department shall be the consultative and support body of the Bank on matters pertaining to security and safety. It shall study and recommend all policies, systems and procedures pertaining to bank security. Likewise, it shall act in cases of actual or attempted fraud in any of the branches of bank units; in cases of civil disturbance, or when extraordinary circumstances warrant it.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Facility & Property Management Department", "code" => "FPMD","description" => "The Facility and Property Management Department shall primarily be responsible for the following:\na)Overall management of the Bank’s building constructions and repairs and renovation projects, including securing the required permits and licenses, contractor selection/ evaluation/ awarding, major building repair/ maintenance/ renovation projects and other related activities.\nb)Property management, such as maintenance of Bank property, handling of building permit application and renewal, business permit monitoring & renewal and other government mandated regulatory requirements.\nc)Handling of other general services, such as moving/ transfers of furniture/ equipment (Old branch site to new site) and Office re-arrangement relative to space planning for all buildings/ properties owned/ leased by the Bank.\nd)Safekeeping of copies of all lease contracts of the Bank branches, offsite banking offices and premises.\ne)Management of all Engineering project-related activities, including field inspections of project sites, management of all project-related expenditures, and coordination with other concerned departments.\nf)Installation, maintenance and repair of utilities systems, such as distribution and internal building systems relative to electrical, water and voice systems.\ng)Installation, maintenance and repair of building and branch equipment I.e. Elevator system, generator sets, pumps and air-conditioning systems.\nh)Installation and repair of Closed Circuit Television (CCTV) for Head office, Bank branches and other banking offices and premises. (CCTV Management shall be handled by Security Department)", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Deposits and Digital Banking Systems Department", "code" => "DDBD","description" => "DDBD executes plan and develop IT related projects concerning deposit, ATM and mobile banking products. The department also provides support and maintenance to the core system and other critical systems related to the mentioned products.", "group_id" =>  $this->getColumnId('group', "Information Technology Group"), "division_id" => $this->getColumnId('division',"Business Application System Support Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Loan Systems Department", "code" => "LSD","description" => "The department is responsible for the application development, maintenance and support for all loan (MCL & Non-MCL) related systems of the bank. It also provides technical support and user technical training.", "group_id" =>  $this->getColumnId('group', "Information Technology Group"), "division_id" => $this->getColumnId('division',"Business Application System Support Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Automation and Bank Office Systems Department", "code" => "ABOSD","description" => "responsible for the automation of bank's manual processes as well as the development and maintenance of back end application of the bank that is neither loans or deposit related. The department also provides technical support and user technical training ", "group_id" =>  $this->getColumnId('group', "Information Technology Group"), "division_id" => $this->getColumnId('division',"Business Application System Support Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Data Center Operations Department", "code" => "DCOD","description" => "Responsible for managing the Bank’s Primary and Secondary Data Center, safeguarding system’s physical and environmental, and Executing batch/report process, backup and restore procedure. ", "group_id" =>  $this->getColumnId('group', "Information Technology Group"), "division_id" => $this->getColumnId('division',"IT Infrastructure Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Desktop, Network and Access Department", "code" => "DNAD","description" => "The Desktop, Network and Access Department (DNAD) of ITG manages and controls the computer hardware and software assets of the Bank. The department also implements, controls and maintains the Bank’s overall network and telecommunications. The team likewise administers the accesses of users to the various Bank’s systems. ", "group_id" =>  $this->getColumnId('group', "Information Technology Group"), "division_id" => $this->getColumnId('division',"IT Infrastructure Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Systems Administration Department", "code" => "SAD","description" => "Provides the required guidelines, practices, policies and procedures in order to ensure the availability of the bank systems and readiness in point of recovery. The manual is intended for Managers and Administrators working with the day-to-day planning and implementation, maintenance of physical and logical servers for flexibility, efficiency, and security towards to ITG Vision and Mission.", "group_id" =>  $this->getColumnId('group', "Information Technology Group"), "division_id" => $this->getColumnId('division',"IT Infrastructure Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Financial Accounting Department", "code" => "FAD","description" => "is responsible for the general bookkeeping of the Bank's transactions including the processing of requests for payment, cash advance, reimbursements.", "group_id" =>  $this->getColumnId('group', "Financial Planning & Control Group"), "division_id" => $this->getColumnId('division',"Accounting Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Loans & Treasury Accounting Department", "code" => "LTAD","description" => "is responsible for the accounting all loan and investment related transactions of the Bank.", "group_id" =>  $this->getColumnId('group', "Financial Planning & Control Group"), "division_id" => $this->getColumnId('division',"Accounting Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Branch Accounting & Reconciliation Department", "code" => "BARD","description" => "is responsible for review and reconciliation of branch transactions and the reconciliation of the Bank's depository and other clearing accounts.", "group_id" =>  $this->getColumnId('group', "Financial Planning & Control Group"), "division_id" => $this->getColumnId('division',"Accounting Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Tax and Regulatory Reports Department", "code" => "TRRD","description" => "Tax and Regulatory Reports Department", "group_id" =>  $this->getColumnId('group', "Financial Planning & Control Group"), "division_id" => $this->getColumnId('division',"Corporate Planning & Regulatory Compliance Reports Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Corporate Planning Department", "code" => "CPD","description" => "Corporate Planning Department", "group_id" =>  $this->getColumnId('group', "Financial Planning & Control Group"), "division_id" => $this->getColumnId('division',"Corporate Planning & Regulatory Compliance Reports Division"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Information Security Department", "code" => "ISD","description" => "Information Security Department ensures that the BANK has no unreported or undisclosed potential losses (including expected and unexpected) through an efficient and effective governance of the bank's information security risks inherent in its business undertakings. It propagates information security risk consciousness across the organization while avoiding an overly risk-averse environment that inhibits business growth.; The Information Security (IS) Program, with it's two areas; 1.) Governance, Risk and Compliance and 2.) Technology Security, is the department's framework, that requires Development of Policies, Procedures and Standards; Risk Management; Awareness and Training; and Independent Review and Monitoring. Activities for each requirement are aligned, consistent and carried out by the department. ", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Systems Development Department", "code" => "SDD","description" => "The Systems Development Department is primarily responsible for the following:\na.Preparation of detailed procedural guidelines and users/manual of operations for various bank’s products and services in accordance with the approved policies.\nAs member of the Product Program Committee, SDD shall be responsible for the implementation of procedural guidelines for the implementation of new product. \nb.Conduct process reviews on key bank operations and recommend process improvement or policy change in coordination with the concerned department/s\nc.Maintenance of Bank Manuals; ensure that Manuals are updated and relevant amendments/revisions in the policies or procedures Manuals are reflected in the Manual.\nd.Reviews and designs all Bank forms; assigns of form number in line with the Bank Form Identification and Control System.\ne.Handles codification and numbering of bank circulars in accordance with the subject matter classification; dissemination of bank circulars via e-mail and uploading in the BMI Portal (except APP which is disseminated only via email).\nf.Safekeeping of all bank approved circulars and manuals.\ng.Provide support to different units of the Bank. ", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Corporate Affairs Office", "code" => "CAO","description" => "Corporate Affairs Office(CAO) is responsible for organizing the meetings of the various Management Committees (ALCO, PERCOM, MANCOM-RISK, and ITMSC) and   Board-Level Committees (EXCOM, CGC); ensure that materials for the meeting agenda are submitted and documents are signed once approved; preparation of the minutes of meeting and the routing of documents for approval of the signatories; and preparation of EXCOM and CGC reports to the Board.; The Department also assists the Corporate Secretary in the preparation for the meetings of the Board of Directors, the Annual Stockholders’ Meeting, and the Annual Organizational Meeting. CAO drafts the Minutes of the Meetings, Secretary’s Certificate, and Directors’ Certificate for the Corporate Secretary.; The CAO also prepares bank circulars pertaining to bank policies and procedures as approved by the Management Committees and the Board of Directors. CAO also issues directives to concerned departments/groups via Administrative Policies and Procedures (APP) and monitors compliance. ", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division',"Corporate Affairs Division"), "created_at" => now(), "updated_at" => now()],
        ]);
    }
}