<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Division;
use App\Models\Group;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HeadOfficeSectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    private function getColumnId(String $column, String $name)
    {
        switch ($column) {
            case 'group':
                $model = Group::class;
                break;
            case 'division':
                $model = Division::class;
                break;
            case 'department':
                $model = Department::class;
                break;
            default:
                $model = null;
                break;
        }

        if ($name === 'N/A') {
            return null;
        }

        $data = $model::where('name', $name)->first();

        return $data->id;
    }

    public function run(): void
    {
        DB::table('sections')->insert([
            ["name" => "IT Risk Management Section", "code" => "ITRMS", "description" => "ITRMS is responsible for the identification, measurement, monitoring, and control of risks for IT business processes or IT service assets.", "group_id" =>  $this->getColumnId('group', "Risk Management Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Enterprise Risk Management Section", "code" => "ERMS", "description" => "ERMS is designed to identify potential events that may affect the Bank and manage risks to be within the Bank’s risk appetite. The ERM also ensures that effective procedures are in place to identify, assess, control and manage risks such as Financial Risks, Compliance Risks, Reputational Risks, Operational Risks, and Strategic Risks. With this, the Risk Management Group (RMG), which reports to the ROC, is mandated to adequately and consistently evaluate, manage, control, and monitor the overall risk profile of the Bank’s activities across different risk areas. This will optimize the risk-reward balance and maximize return on capital. The RMG also has the responsibility to recommend to the appropriate body all risk policies across full-range of risks to which the Bank is exposed.", "group_id" =>  $this->getColumnId('group', "Risk Management Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Treasury Operations Unit", "code" => "TOU", "description" => "TOU is responsible for the following: \n a)Confirming, documenting and settling all dealt transactions; \n b)Monitoring, updating and reconciling investment inventory including monitoring of interest payments of the securities; \n c)Creation of Overnight Reverse Repurchase (RRP)/ Term Deposit Facility (TDF) auction and Overnight Deposit Facility (ODF) placements thru BSP MOS;\n d)Interbank Call Loans (IBCL) Creation, Settlement & Reporting;\n e)Handles the safekeeping and custody of petty cash fund (PCF) of Treasury Group;\n f)Booking of air travel including preparation of request for payment of the corporate credit cards; \n g)Documenting depository accounts opening, updating, closure and online banking enrollment.", "group_id" =>  $this->getColumnId('group', "Loans & Treasury Operations Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Receiving & Dispatching Section", "code" => "RDS", "description" => "The Receiving and Dispatching Section is primarily responsible for the following: \n Maintaining proper receipt and distribution of all Company Documents/FF&E transmitted from Branches and other external addresses to Head Office Departments. \n Monitoring and tracking of all dispatched Company Documents/FF&E from Head Office Departments to Branches and other external addresses, and ensuring all shipments are delivered to the respective recipients. \n Providing messengerial services to Head Office Departments to support their dealings with clients, and other third party engagements within Metro Manila.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "General Services Admin Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Purchasing Unit", "code" => "PU", "description" => "The Purchasing Section is primarily responsible for the following: \n Purchase the best goods and services to meet the business/operational needs of the Bank, which includes testing and evaluation of various commodities to ensure proper balance of quality and cost. \n Negotiation with supplier for the best possible price for goods and services. \n Make the goods and services available when and where they are needed by expediting purchases and deliveries. \n Ensure the availability or supply of needed goods and services.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "General Services Admin Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Admin and Records Management Section", "code" => "ARMS", "description" => "The Admin and Records Management Section is primarily responsible for the following: \n Prompt and timely distribution/ issuance of office supplies and forms to all requesting departments and branches. \n Effective utilization of the Bank’s resources through proper monitoring, recording and control of issuances. \n Management of inventory costs at reasonable levels through the implementation of appropriate stocking control measures, (e.g. establishment of maximum stock levels, minimum reorder point’s consideration, etc.)\n Maintenance of accurate and updated inventory records for audit purposes.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "IT Service Delivery Section", "code" => "ITSD", "description" => "Service Delivery is one of the functions of the IT Group which is created to provide a strategic central point of contact for Bank of Makati (A Savings Bank) business users by providing immediate technical support, advice and guidance to them. It also aims to facilitate the restoration of normal service operation as quickly as possible through efficient management of incidents and service requests including use of work-around, prioritization, and proper escalation and monitoring. Service Delivery shall ensure that incidents and service requests are handled in a timely manner in accordance with the Service Level Agreement. Service Delivery shall also produce significant reports based on captured information to serve as tool for process improvement and reference for management reviews. ", "group_id" =>  $this->getColumnId('group', "Information Technology Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Quality Management Section", "code" => "QMS", "description" => "QMS is responsible for ensuring that the product quality is consistent and adherence to the defined quality standards and quality objectives of BASSD and ITG through its four main components: quality planning, quality control, quality assurance and quality improvement.", "group_id" =>  $this->getColumnId('group', "Information Technology Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Network Security Administrator Section", "code" => "NSA", "description" => "Network Security Administrator Section", "group_id" =>  $this->getColumnId('group', "Information Technology Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Data Protection Officer", "code" => "DPO", "description" => "Responsible for the overall management of Bank's compliance to the Data Privacy Act of 2012.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Payroll Unit", "code" => "PRU", "description" => "Manages the accurate computation of employees' payroll as well as the timely crediting of salaries, loans, incentives, benefits, and final pays. It is also responsible for the timely payment and remittance of mandatory deductions from employees' compensation and submission of reports to SSS, PHIC, HDMF and the BIR.", "group_id" =>  $this->getColumnId('group', "Treasury Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "N/A"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Vehicle Loan Unit", "code" => "VLU", "description" => "handles all auto loans and luxury bikes referred by accredited car dealers and branches", "group_id" =>  $this->getColumnId('group', "Corporate & Retail Lending Group"), "division_id" => $this->getColumnId('division', "Real Estate & Consumer Lending Division"), "department_id" => $this->getColumnId('department', "Consumer Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Multipurpose Loans Unit (Branch & Company Accredited)", "code" => "MLU", "description" => "handles Personal Loans and Power Payday referred by branches and accredited companies", "group_id" =>  $this->getColumnId('group', "Corporate & Retail Lending Group"), "division_id" => $this->getColumnId('division', "Real Estate & Consumer Lending Division"), "department_id" => $this->getColumnId('department', "Consumer Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Remedial Management Unit", "code" => "RMU", "description" => "Offers remedial options to let the pastdue borrower settle their obligation; Initiates legal action for the filing of necessary case to collect from the borrowers ", "group_id" =>  $this->getColumnId('group', "Repo Marketing & Disposal Management Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Remedial & Disposal Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Ropa Disposal Unit", "code" => "RDU", "description" => "Responsible in marketing the acquired assets of the bank; Documentation of sale through Sales Contract Receivable (SCR), negotiated sale and bidding", "group_id" =>  $this->getColumnId('group', "Repo Marketing & Disposal Management Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Remedial & Disposal Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Asset Management Unit", "code" => "AMU", "description" => "Process the assessment, registration and annotation, payments, consolidation /transfer        of ownership of title in the name of the bank \n Responsible for preservation and management of the acquired assets of the bank", "group_id" =>  $this->getColumnId('group', "Repo Marketing & Disposal Management Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Remedial & Disposal Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Loans Booking & Releasing Section", "code" => "LBRS", "description" => "a) In charge on the processing of loans booking and releasing for both housing and business loan accounts (new availment, roll-overs, extensions, restructuring and the like). \n b)Ensures that all accounts requests for booking and releasing are properly booked and disbursed within the day with clearance from Credit Control Section (CCS).\n c)Regularly send Covered Transaction Report (CTR) to Compliance Group for accounts with loan amount of more than 500K. \n d)Ensures proper tagging of loan details in the system (Finacle) including loan amortization schedule and other pertinent details related to booking and releasing.\n e)Monitors and reports BSP personnel with existing loan availment with the bank to the Compliance Group.", "group_id" =>  $this->getColumnId('group', "Loans & Treasury Operations Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Loans Operations Department 2"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Securities & Collateral Custodianship Section", "code" => "SCCS", "description" => "a)Oversees the physical safekeeping, filing, protection and tracking/monitoring of documents, collateral, records and other items filed in credit folders stored in the collateral vault. \n b)In charge on safekeeping of credit folders and ensures that all pertinent documents attached in the credit folder are complete, properly scanned/groomed and monitored. The Credit Control Section (CCS) should ensure that all documents forwarded to LOD2-SCCU is complete and in order.\n c)In charge on safekeeping of original collateral documents, release of collaterals, and monitoring of fully paid accounts.\n d)Responsible for the management of securities held as collateral, items held for safekeeping as well as the release, retrieval, or pull-out for borrowings and releasing of collateral/s and/or loan documents\n e)Ensures that all borrowed documents are approved by the approving authority and monitors the returns of the documents within the prescribed period.\n f)In charge of the retrieval of documents only to authorize groups/individuals who have been granted access to vault records.\n g)Ensures all existing and new release documents for back-up and culled matured docs forwarded to General Services Dept. - Records Management Unit (RMU) for warehousing.\n h)Ensures all collaterals are properly and timely encoded and tagged in the system (Finacle)\n i)Ensures the proper and correct destruction of loan documents for accounts that are already culled for more than 10 years.", "group_id" =>  $this->getColumnId('group', "Loans & Treasury Operations Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Loans Operations Department 2"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Registration & Annotation Section", "code" => "RAS", "description" => "a)Handles the registration and annotation of mortgages for housing and business loan accounts exclusively for NCR area only. Outside NCR can be accommodated subject for approval of the approving body. \n b)The Credit Control Section (CCS) is the one handling the registration outside NCR via the bank's accredited service provider.\n c)Ensures that all encumbrances / liens must be cancelled in favor of the bank.\n d)Handles the transfer of ownership of the TCT/CCT from the previous owner to the new owner / mortgagor.\n e)Handles the following administrative tasks related to the collateral such as annotation of affidavits, correction of the title details and the like. \n f)Facilitates the computation of registration expenses from the requesting unit.\n g)Prepares eDST certification and payment as requirement for REM registration. ", "group_id" =>  $this->getColumnId('group', "Loans & Treasury Operations Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Loans Operations Department 2"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Insurance Management Section", "code" => "IMS", "description" => "a)Handles the procurement and enrollment of insurance for both housing and business loan accounts.\n b)Responsible for the accreditation of insurance providers both for life and non-life.\n c)Coordinates with the Insurance Providers for both the bank's claims and client's beneficiaries such as death, accident, fire and other related insurance concerns.\n d)Ensures that all endorsed insurance policies submitted by the borrower is under Bank of Makati (BMI) as the mortgagee bank.\n e)Monitoring of Renewals of Insurance and updating of Payment to Insurance Providers of the borrower/s. \n f)Monitoring of Payments for the Premium of Insurance and providing Statement of Account of the borrower/s. \n g)Ensures that all unpaid insurance premiums are collected prior the full payment of the loan.\n h)Monitoring the Excess Limit per Insurance Provider", "group_id" =>  $this->getColumnId('group', "Loans & Treasury Operations Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Loans Operations Department 2"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Credit Evaluation Section", "code" => "CES", "description" => "evaluates financial condition of the client and determines actual financial requirements. Qualify the risk profile of business loan borrowers to effectively screen out bad accounts and identify the level of risk of potentially problematic accounts.  ", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division', "Credit Division"), "department_id" => $this->getColumnId('department', "Credit Evaluation & Policy Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Credit Control Section", "code" => "CCS", "description" => "Its over-all function is to validate, review, monitor and ensure that all documents submitted by CRLG personnel handling Business and Housing Loans are appropriate, complete and in order prior any disbursement of Loans granted to the Borrower. The section also handles the facilitation of annotation and registration of mortgage with Registry of Deeds located outside NCR thru the bank's accredited service provider. ", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division', "Credit Division"), "department_id" => $this->getColumnId('department', "Credit Evaluation & Policy Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Area Operations Office", "code" => "AOO", "description" => "Ensures day-to-day operations processing shall run smoothly and observes policies, procedures and controls\n Supervises the BOH and tellers in the branch\n Monitors the strict compliance of all branches to the Bank's policies and procedures and the rules and regulations of government regulatory agencies\n Suggest new or revision on existing branch policies and procedures to improve operational processes/ customer service\n Monitors CIV limits of each branch and extension of branch closure", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division', "Branch & Central Operations Division"), "department_id" => $this->getColumnId('department', "Branch Banking Operations Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Quality Assurance and Support Section", "code" => "QASS", "description" => "Assist the Department in fulfilling its objective to ensure that the branch operations are in accordance to the policies and procedures set by the bank by giving quality review of the operations, checking adequacy of existing internal controls, reviewing compliance of branches to policies/guidelines in preparation for branch internal/external audits and deployment of relievers to branches.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division', "Branch & Central Operations Division"), "department_id" => $this->getColumnId('department', "Branch Banking Operations Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "PDC Warehousing and Central Processing Unit", "code" => "PWCPU", "description" => "Handles the acceptance, warehousing, monitoring and prompt negotiation of Postdated Checks (PDCs) issued by clients for payment for their loan obligations. Central Processing is created to centralize the processing of loan payments and releases of all BMI and Micro -Finance branches and other fund transfer activities such as authorized.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division', "Branch & Central Operations Division"), "department_id" => $this->getColumnId('department', "Central Support Operations Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Central Clearing and Verification Unit", "code" => "CCVU", "description" => "CCVU is in-charge for the Bank's compliance with PCHC clearing rules and regulations, processing of checks (inward, outward and returned checks), signature verification and fraud detection.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division', "Branch & Central Operations Division"), "department_id" => $this->getColumnId('department', "Central Support Operations Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "E-Banking Unit", "code" => "EBU", "description" => "E-Banking Unit was created as BMI ventures to offer E-banking services such as ATM, Mobile Banking, Cash Agency, Inter-bank Electronic Fund Transfer to its clients. lts membership to BancNet expands its services as an issuer to other cardholders with the aim not only to cater CASA clients via 24 x 7 online access but also to increase public exposure and serve other bank cardholders.", "group_id" =>  $this->getColumnId('group', "N/A"), "division_id" => $this->getColumnId('division', "Branch & Central Operations Division"), "department_id" => $this->getColumnId('department', "Central Support Operations Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Recruitment & Selection", "code" => "RS", "description" => "responsible for identifying the need for a job, analyzing job requirement of the position, reviewing applications, screening, advertising the position a) and choosing the most suitable candidate for the job. It shall also ensure 100% accuracy and completeness on the employment contracts and other pre-employment documentations prior to on-boarding. It shall act as 201 File Custodian for every active employee.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Human Resources Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Employee Relations & Benefits", "code" => "ERB", "description" => "responsible for attending to all employees' queries and work-related concerns while under the employ of the Bank. It shall ensure every employee's 100% adherence to the Bank's Code of Conduct & Discipline. It shall ensure faster resolution for every employee case and shall coordinate and liaise with the Bank's Employee Union Federation to address any potential employee issues or grievance. The section is also responsible for the administration of all employee benefits including government mandatory benefits such as Pagibig, Philhealth and SSS. Likewise, it shall assist the Department Head in identifying and enhancing the Bank's employee benefit program and in executing the Bank's Corporate Social Responsibility (CSR) Activities. ", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Human Resources Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Employee Records & HRIS", "code" => "ERH", "description" => "responsible for the overseeing the Bank's Human Resources Information System where employee's timekeeping and attendance is processed. It shall address and coordinate with the vendor any gap or identified system issue to ensure 100% functionality. Likewise, the section is responsible for ensuring 100% timeliness and accuracy of all HR Management Reports such as but not limited to Annual Manpower Complement Report, PDIC and other mandatory reports for submission to BSP including processing of employee clearances. ", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Human Resources Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Organizational Development", "code" => "OD", "description" => "responsible for overseeing the Bank's Performance Management Development System (PMDS) where individual job descriptions are reviewed and analyzed for competency requirements and individual online Performance Commitment Form for all positions are updated in the system. It shall likewise maintain a database of the Performance Appraisal Reports of all employees and do proper coordination with the Heads of Office as well as with ER & Benefits Section to ensure that proper action shall be taken in view of the employee's performance. The Section is also in-charge of screening recommended employees for promotions through validation of their employment profile, performance history and by administering a number of psychological exams that aim to identify the candidate's strengths and weaknesses. It also liaises with L&DD in identifying competency gaps and provide recommendations on possible interventions to support the employee's personal and professional development.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Organizational and People Development Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Training Section", "code" => "TS", "description" => "Identify and prioritize the Bank's human resource training and development needs; Plan, develop, conduct, and evaluate training and development programs in order to raise up the level of skill and the quality corporate culture within the Bank. ", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Organizational and People Development Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Security Officer (Operation Unit)", "code" => "OU", "description" => "Provides strategic plans and direction for the operations of Security Office to ensure that security programs are strictly implemented and complied with, in order to prevent losses arising from internal and external fraud, robberies, other bank crimes and other natural or man-made hazards.\n Ensures the implementation of Security Program particularly in the responses to alarm signals, emergency posting of guards and inspections of branches. \n Establishes an effective working relationship with BSP, PNP, BFP, AFP and other law enforcement agencies in the prevention of bank crimes and other natural and man- made hazards.\n Prepares data base of Bank’s Crimes and Losses, periodic and special reports, manuals and correspondence. \n Ensures that no classified information, documents and interests are disclosed to unauthorized individuals.\n Develops operations plan (OPLAN), contingency plan, disaster management plan and emergency protocols during crisis.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Safety & Security Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Administrative Unit", "code" => "AU", "description" => "Provides strategic plans and direction for the administration of security program, particularly in overseeing and implementation of procedures. \n Develops work priorities and coordinate the acquisition of administrative services such as monitoring of security provider’s contract, supplies, security services and security devices/equipment.\n Supervise the contracted security personnel assigned in the Bank. \n Oversees and coordinates security office administrative procedures and review, evaluate and implement new procedures. \n Formulates and plan for office services such as accommodation, relocation's, equipment, supplies forms, disposal of assets, parking, maintenance and services. \n Prepares operating budget and maintain inventory and budgetary controls.\n Formulate data and prepare periodic and special reports, manuals and correspondence.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Safety & Security Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Investigation Unit", "code" => "IU", "description" => "Conducts investigation of cases referred, including background investigation and surveillance operations. \n Assist in the implementation of the physical security standards to ensure the Bank’s properties are protected from burglary, vandalism and intrusion.\n Assist in the installation of security alarm/devices, CCTV and access control in compliance to the standard of the Bank, including the dismantling and re-installation of security devices during the renovation and relocation of branches.\n Assist in monitoring the alarm system and CCTV of Bank’s offices to ensure they are in place and working.\n Assist in the conduct of security audit, threat assessment of branches and other Bank’s offices, security survey of proposed branches relocation.", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Safety & Security Department"), "created_at" => now(), "updated_at" => now()],
            ["name" => "Safety Unit", "code" => "SU", "description" => "Performs regular inspection to ensure free hazard in the workplace. \n Assists the Head in the creation and implementation of Health, Safety & Environmental (HSE) Program of the Bank.\n Monitors HSE performance to identify areas for improvement and ensures that appropriate corrective /preventive actions are taken. \n Implements the policies and procedures to provide a safe and secure business operation;\n Enforces and promotes safe working practices, safety guidelines at all times and ensure lost time incidents are kept to a minimum;\n Investigate the reported accident and complaint of hazardous working environment;\n Inspects workplaces based on the approved schedule for the year to ensure safe working condition and risk-free atmosphere. \n Checks the condition of fire alarm system and other fire equipment;\n Recommends immediate removal of hazardous waste and materials; \n Monitors employees and ensure adherence to the safety guidelines; \n Classifies physical health hazards and effects; \n Prepares budget proposals for accident prevention, First Aid Training (NCR) and endorse the same to immediate head for review and initial approval.\n Together with the Head, ensures that Emergency Response Plans are in place;", "group_id" =>  $this->getColumnId('group', "Corporate Services Group"), "division_id" => $this->getColumnId('division', "N/A"), "department_id" => $this->getColumnId('department', "Safety & Security Department"), "created_at" => now(), "updated_at" => now()],
        ]);
    }
}
